# Use a lightweight Python base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Create a placeholder .env file that will be overridden in k8s
RUN touch .env
# Copy the application code
COPY app.py .

# Expose the port the Flask app will run on
EXPOSE 5000

# Command to run the application using Gunicorn for production
# Gunicorn will run the app with 4 worker processes.
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "4", "app:app"]
